# -*- coding: utf-8 -*-
"""
Parse a FreeCAD OpenSCAD CSG file into AST nodes
------------------------------------------------

Usage:
    from ast_nodes import AstNode, Sphere, Hull, MultMatrix, ...
    nodes = parse_csg_file_to_AST_nodes(filename)
"""

import re
from freecad.OpenSCAD_Ext.parsers.csg_parser.ast_nodes import *
from freecad.OpenSCAD_Ext.logger.Workbench_logger import write_log

# -------------------------------------------------
# Helper: parse key=value pairs from CSG
# -------------------------------------------------
def parse_csg_params(param_str):
    """
    Converts a param string like 'r=10, $fn=6' to a dict
    Numeric strings are converted to numbers for FC params
    """
    params = {}
    if not param_str:
        return params

    for part in param_str.split(","):
        part = part.strip()
        if "=" not in part:
            params[part] = None
            continue
        k, v = part.split("=", 1)
        k = k.strip()
        v = v.strip()
        # Convert numeric strings
        try:
            params[k] = int(v)
        except ValueError:
            try:
                params[k] = float(v)
            except ValueError:
                params[k] = v  # keep string
    return params

# -------------------------------------------------
# Recursive parser
# -------------------------------------------------
def parse_csg_lines(lines, start=0):
    """
    Recursively parse lines from CSG file
    Returns: (list of AstNode, next_line_index)
    """
    nodes = []
    i = start
    while i < len(lines):
        line = lines[i].strip()
        if not line:
            i += 1
            continue
        if line.startswith("}"):
            return nodes, i + 1

        # Extract node type and params
        m = re.match(r"(\w+)\s*\((.*)\)\s*({)?", line)
        if not m:
            write_log("CSG_PARSE", f"Skipping unrecognized line: {line}")
            i += 1
            continue

        node_type, param_str, brace = m.groups()
        node_type = node_type.lower()
        csg_params = param_str.strip()
        params = {}

        # Handle special nodes
        if node_type == "multmatrix":
            try:
                matrix = eval(csg_params)  # safe: generated by OpenSCAD CSG
                params = {"matrix": matrix}
            except Exception:
                params = {"matrix": [[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]]}
            # Store flat string for OpenSCAD fallback
            csg_params = {"matrix": csg_params}
            has_children = True
        else:
            params = parse_csg_params(param_str)
            has_children = bool(brace)

        # Determine class
        cls = {
            "cube": Cube,
            "sphere": Sphere,
            "cylinder": Cylinder,
            "polyhedron": Polyhedron,
            "circle": Circle,
            "square": Square,
            "polygon": Polygon,
            "union": Union,
            "difference": Difference,
            "intersection": Intersection,
            "hull": Hull,
            "minkowski": Minkowski,
            "group": Group,
            "translate": Translate,
            "rotate": Rotate,
            "scale": Scale,
            "multmatrix": MultMatrix,
            "linear_extrude": LinearExtrude,
            "rotate_extrude": RotateExtrude,
        }.get(node_type, AstNode)

        # Prepare children
        children = []
        if has_children:
            children, i = parse_csg_lines(lines, i + 1)
        else:
            i += 1

        # Instantiate node
        try:
            if node_type == "sphere":
                r = params.get("r", 1)
                fn = params.get("$fn")
                fa = params.get("$fa")
                fs = params.get("$fs")
                node = cls(r=r, fn=fn, fa=fa, fs=fs, params=params, csg_params=csg_params)
            elif node_type == "cube":
                size = params.get("size", [1,1,1])
                center = params.get("center", False)
                node = cls(size=size, center=center, params=params, csg_params=csg_params)
            elif node_type == "cylinder":
                h = params.get("h", 1)
                r = params.get("r")
                r1 = params.get("r1")
                r2 = params.get("r2")
                center = params.get("center", False)
                fn = params.get("$fn")
                fa = params.get("$fa")
                fs = params.get("$fs")
                node = cls(h=h, r=r, r1=r1, r2=r2, center=center, fn=fn, fa=fa, fs=fs, params=params, csg_params=csg_params)
            elif node_type == "multmatrix":
                node = cls(matrix=params.get("matrix"), children=children, params=params, csg_params=csg_params)
            elif node_type in ("translate", "rotate", "scale"):
                node = cls(vector=params.get("vector"), angle=params.get("angle") if node_type=="rotate" else None,
                           children=children, params=params, csg_params=csg_params)
            else:
                node = cls(children=children, params=params, csg_params=csg_params)
        except Exception as e:
            write_log("CSG_PARSE", f"Failed to instantiate node {node_type}: {e}")
            node = AstNode(node_type, params=params, csg_params=csg_params, children=children)

        nodes.append(node)

    return nodes, i

# -------------------------------------------------
# Main parser
# -------------------------------------------------
def parse_csg_file_to_AST_nodes(filename):
    """
    Reads a .csg file and returns a list of AstNode objects
    """
    write_log("CSG_PARSE", f"Parsing CSG file: {filename}")
    with open(filename, "r") as f:
        lines = f.readlines()
    nodes, _ = parse_csg_lines(lines, start=0)
    write_log("CSG_PARSE", f"Parsed {len(nodes)} top-level nodes")
    return nodes

